MongoMvc/Controllers/FilesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MongoMvc.Model;
using MongoMvc.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using MongoMvc.Repository;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace MongoMvc.Controllers
{
    [Authorize]
    public class FilesController : Controller
    {

        private readonly IStorageService _StorageService;
                
        public FilesController(IHostingEnvironment AppEnvironment)
        {
            _StorageService = new LocalFileStorageService(AppEnvironment);
        }

        // GET: /<controller>/
        public IActionResult WorkSchedules()
        {
            return View(_StorageService.GetAllFiles("workschedule"));
        }

        public IActionResult Instructions()
        {
            return View(_StorageService.GetAllFiles("instructions"));
        }

        [HttpGet]
        public async Task<IActionResult> CreateWorkSchedule()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateWorkSchedule(List<IFormFile> files)
        {
            if (files.Count != 0)
            {
                foreach (IFormFile file in files)
                {                    
                    await _StorageService.UploadAsync("workschedule", file);
                }
            }
            return RedirectToAction("WorkSchedules");
        }

        [HttpGet]
        public async Task<IActionResult> CreateInstruction()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateInstruction(List<IFormFile> files)
        {
            if (files.Count != 0)
            {
                foreach (IFormFile file in files)
                {
                    await _StorageService.UploadAsync("instructions", file);
                }
            }
            return RedirectToAction("Instructions");
        }

        [HttpGet]
        public IActionResult DeleteInstruction(String fileName)
        {
            var file = _StorageService.GetAllFiles("instructions").Where(f => f.Name == fileName).FirstOrDefault();
            return View(file);
        }

        [HttpPost, ActionName("DeleteInstruction")]
        public IActionResult ConfirmDeleteInstruction(String fileName)
        {
            _StorageService.DeleteFile(Path.Combine("instructions", fileName));
            return RedirectToAction("Instructions");
        }

        [HttpGet]
        public IActionResult DeleteWorkSchedule(String fileName)
        {
            var file = _StorageService.GetAllFiles("workschedule").Where(f => f.Name == fileName).FirstOrDefault();
            return View(file);
        }

        [HttpPost, ActionName("DeleteWorkSchedule")]
        public IActionResult ConfirmDeleteWorkSchedule(String fileName)
        {
            _StorageService.DeleteFile(Path.Combine("workschedule", fileName));
            return RedirectToAction("WorkSchedules");
        }
    }
}

MongoMvc/Controllers/LecturerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MongoMvc.Repository;
using MongoMvc.Model;
using Microsoft.AspNetCore.Authorization;

namespace MongoMvc.Controllers
{
    [Authorize]
    public class LecturerController : Controller
    {        
        private readonly ILecturerRepository _LecturerRepository;
        private readonly IDisciplineRepository _DisciplineRepository;

        public LecturerController(ILecturerRepository LecturerRepository, IDisciplineRepository DisciplineRepository)
        {            
            _LecturerRepository = LecturerRepository;
            _DisciplineRepository = DisciplineRepository;
        }
               

        public async Task<IActionResult> Read()
        {          
            return View(await _LecturerRepository.GetAllAsync());
        }        

        [HttpGet]
        public IActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Lecturer lc)
        {                                                         
            await _LecturerRepository.AddAsync(lc);            
            return RedirectToAction("Read");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if(id == null)
            {
                return new BadRequestResult();
            }
            Lecturer lc = await _LecturerRepository.GetByIdAsync(id);
            if(lc == null)
            {
                return new NotFoundResult();
            }            
            return View(lc);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Lecturer lc)
        {            
            await _LecturerRepository.UpdateAsync(lc.Id, lc);            
            return RedirectToAction("Read");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            Lecturer lc = await _LecturerRepository.GetByIdAsync(id);
            if (lc == null)
            {
                return new NotFoundResult();
            }            
            return View(lc);
        }

        [HttpPost, ActionName("Delete")]       
        public async Task<IActionResult> ConfirmDelete(string id, bool check = false)
        {
            var lc = _LecturerRepository.GetById(id);
            if (check)
            {
                _DisciplineRepository.RemoveLecturerAsync(id, lc);
                
            }
            await _LecturerRepository.RemoveByIdAsync(id);
            return RedirectToAction("Read");
        }        
    }
}

MongoMvc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Методичне забезпечення ПМ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Курси/Спеціалізації<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Курси</li>
                            <li><a href="~/Home/Course/1">&#8544 Курс</a></li>
                            <li><a href="~/Home/Course/2">&#8545 Курс</a></li>
                            <li><a href="~/Home/Course/3">&#8546 Курс</a></li>
                            <li><a href="~/Home/Course/4">&#8547 Курс</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Спеціалізації</li>
                            <li><a href="~/Home/Course/5">Математичне і комп'ютерне моделювання</a></li>
                            <li><a href="~/Home/Course/6">Математичне моделювання мікро- і нано систем</a></li>
                            <li><a href="~/Home/Course/7">Обчислювальна механіка</a></li>
                            <li><a href="~/Home/Course/8">Комп'ютерні науки та інформаційні технології</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Read"> Усі дисципліни </a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Lecturer" asp-action="Read"> Викладачі </a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Документи<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Files" asp-action="Instructions"> Методичні вказівки </a></li>
                                <li><a asp-area="" asp-controller="Files" asp-action="WorkSchedules"> Робочі програми </a></li>
                            </ul>
                        </li>
                    }
                </ul>

                @Html.AntiForgeryToken()
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Вийти", "LogOut", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Увійти", "Login", "Account")</li>
                    }
                </ul>
                
                <form class="navbar-form nav navbar-nav navbar-right input-group" asp-controller="Home" asp-action="Read">
                    <div class="form-group">
                        <input type="text" class="form-control input-group" placeholder="Шукати дисципліну" name="searchWord" value="@ViewData["SearchWord"]">
                    </div>
                    <span class="input-group-btn form-group">                        
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                </form>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Методичне забезпечення дисциплін кафедри "Прикладна математика"</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>